# Generated by Django 4.1.4 on 2023-06-10 02:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cpmk',
            fields=[
                ('id_tabel_cpmk', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_cpmk', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^\\S+$', 'Tidak boleh memiliki spasi')])),
                ('tahun_angkatan', models.IntegerField()),
                ('keterangan_cpmk', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='detailpenilaian',
            fields=[
                ('id_detail_penilaian', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_tahap', models.CharField(choices=[('Bimbingan', 'Bimbingan'), ('Seminar Proposal', 'Seminar Proposal'), ('Seminar Hasil', 'Seminar Hasil')], max_length=60)),
                ('hasil_review', models.TextField(blank=True)),
                ('status_kelulusan', models.CharField(choices=[('Lulus', 'Lulus'), ('Tidak Lulus', 'Tidak Lulus')], max_length=60)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('nip', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('photo_file', models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photo_dosen/')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jadwal_semester',
            fields=[
                ('id_jadwal_semester', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_semester', models.CharField(choices=[('Semester Ganjil', 'Semester Ganjil'), ('Semester Genap', 'Semester Genap')], max_length=60)),
                ('tahun_semester', models.CharField(max_length=100)),
                ('tanggal_awal_semester', models.DateField(default=django.utils.timezone.now, null=True)),
                ('tanggal_akhir_semester', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kompartemen',
            fields=[
                ('id_kompartemen', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_kompartemen', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('angkatan', models.IntegerField()),
                ('photo_file', models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photo_mhs/')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester_daftar_skripsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripsi_app.jadwal_semester')),
            ],
        ),
        migrations.CreateModel(
            name='notifikasi',
            fields=[
                ('id_notifikasi', models.BigAutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=100, null=True)),
                ('nim', models.CharField(max_length=100, null=True)),
                ('messages', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='usulantopik',
            fields=[
                ('id_usulan_topik', models.BigAutoField(primary_key=True, serialize=False)),
                ('permintaan_dosen_2', models.CharField(max_length=100, null=True)),
                ('judul_topik', models.CharField(max_length=60)),
                ('status_pengajuan', models.CharField(choices=[('Usulan Topik Pertama', 'Usulan Topik Pertama'), ('Pengajuan Kembali Usulan Topik', 'Pengajuan Kembali Usulan Topik')], default='Usulan Topik Pertama', max_length=60)),
                ('file_topik', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='topik_mahasiswa/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('keterangan', models.TextField(blank=True)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.mahasiswa')),
                ('permintaan_dosen_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='skripsi_app.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='sub_cpmk',
            fields=[
                ('id_tabel_sub_cpmk', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_sub_cpmk', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^\\S+$', 'Tidak boleh memiliki spasi')])),
                ('tahun_angkatan', models.IntegerField()),
                ('keterangan_sub_cpmk', models.TextField(blank=True)),
                ('bobot_persen_sempro', models.CharField(blank=True, max_length=60)),
                ('bobot_sempro', models.FloatField(blank=True, default=0)),
                ('bobot_persen_semhas', models.CharField(blank=True, max_length=60)),
                ('bobot_semhas', models.FloatField(blank=True, default=0)),
                ('bobot_persen_pembimbing', models.CharField(blank=True, max_length=60)),
                ('bobot_pembimbing', models.FloatField(blank=True, default=0)),
                ('id_cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.cpmk')),
                ('id_nama_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripsi_app.jadwal_semester')),
            ],
        ),
        migrations.CreateModel(
            name='roledosen',
            fields=[
                ('id_role_dosen', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Pembimbing 1', 'Pembimbing 1'), ('Pembimbing 2', 'Pembimbing 2'), ('Penguji Seminar Proposal 1', 'Penguji Seminar Proposal 1'), ('Penguji Seminar Proposal 2', 'Penguji Seminar Proposal 2'), ('Penguji Seminar Hasil 1', 'Penguji Seminar Hasil 1'), ('Penguji Seminar Hasil 2', 'Penguji Seminar Hasil 2')], max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Finished', 'Finished')], max_length=200)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.mahasiswa')),
                ('nip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='proposal',
            fields=[
                ('id_proposal', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_tahap', models.CharField(choices=[('Proposal Awal', 'Proposal Awal '), ('Proposal Awal (Revisi Seminar Proposal)', 'Proposal Awal (Revisi Seminar Proposal)'), ('Laporan Akhir', 'Laporan Akhir '), ('Laporan Akhir (Revisi Seminar Hasil)', 'Laporan Akhir (evisi Seminar Hasil)')], max_length=60)),
                ('judul_proposal', models.CharField(max_length=60)),
                ('file_proposal', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='proposal_mahasiswa/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('keterangan', models.TextField(blank=True)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='penilaian',
            fields=[
                ('id_penilaian', models.BigAutoField(primary_key=True, serialize=False)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('id_detail_penilaian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.detailpenilaian')),
                ('id_sub_cpmk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.sub_cpmk')),
            ],
        ),
        migrations.CreateModel(
            name='kompartemendosen',
            fields=[
                ('id_dosen_kompartemen', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_kompartemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.kompartemen')),
                ('nip', models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='jadwal_seminar',
            fields=[
                ('id_jadwal_seminar', models.BigAutoField(primary_key=True, serialize=False)),
                ('tahap_seminar', models.CharField(choices=[('Seminar Proposal', 'Seminar Proposal'), ('Seminar Hasil', 'Seminar Hasil')], max_length=60, null=True)),
                ('ruang_seminar', models.CharField(choices=[('Ruang Seminar A', 'Ruang Seminar A'), ('Ruang Seminar B', 'Ruang Seminar B'), ('Ruang Meeting A', 'Ruang Meeting A')], max_length=60, null=True)),
                ('tanggal_seminar', models.DateField(default=django.utils.timezone.now, null=True)),
                ('waktu_seminar', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('dosen_pembimbing_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_1', to='skripsi_app.roledosen')),
                ('dosen_pembimbing_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_2', to='skripsi_app.roledosen')),
                ('dosen_penguji_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penguji_1', to='skripsi_app.roledosen')),
                ('dosen_penguji_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penguji_2', to='skripsi_app.roledosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='skripsi_app.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='evaluasitopik',
            fields=[
                ('id_evaluasi_topik', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_topik', models.CharField(choices=[('ACC', 'ACC'), ('Revisi', 'Revisi'), ('Submit', 'Submit'), ('Dalam Evaluasi', 'Dalam Evaluasi')], default='Submit', max_length=60)),
                ('catatan', models.TextField()),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('id_dosen_kompartemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.kompartemendosen')),
                ('id_usulan_topik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.usulantopik')),
            ],
        ),
        migrations.AddField(
            model_name='detailpenilaian',
            name='id_jadwal_seminar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.jadwal_seminar'),
        ),
        migrations.AddField(
            model_name='detailpenilaian',
            name='id_role_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.roledosen'),
        ),
        migrations.AddField(
            model_name='cpmk',
            name='id_nama_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripsi_app.jadwal_semester'),
        ),
        migrations.CreateModel(
            name='bimbingan',
            fields=[
                ('id_bimbingan', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_bimbingan', models.CharField(choices=[('ACC', 'ACC'), ('Revisi', 'Revisi'), ('Submit', 'Submit'), ('Dalam Evaluasi', 'Dalam Evaluasi')], default='Submit', max_length=60)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('id_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.proposal')),
                ('id_role_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.roledosen')),
            ],
        ),
    ]
