# Generated by Django 4.1.4 on 2023-05-13 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='id_sub_cpmk',
        ),
        migrations.AddField(
            model_name='detailpenilaian',
            name='id_jadwal_seminar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.jadwal_seminar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_cpmk',
            name='id_jadwal_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripsi_app.jadwal_semester'),
        ),
        migrations.AlterField(
            model_name='sub_cpmk',
            name='id_sub_cpmk',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^\\S+$', 'Tidak boleh memiliki spasi')]),
        ),
        migrations.AddField(
            model_name='sub_cpmk',
            name='id_tabel_sub_cpmk',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_cpmk',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='id_detail_penilaian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.detailpenilaian'),
        ),

    ]
