# Generated by Django 4.1.4 on 2023-05-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0002_remove_penilaian_id_sub_cpmk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_cpmk',
            name='id_tabel_sub_cpmk',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
