# Generated by Django 4.1.4 on 2023-05-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0003_alter_sub_cpmk_id_tabel_sub_cpmk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_cpmk',
            name='id_sub_cpmk',
        ),
    ]
