# Generated by Django 4.1.4 on 2023-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0005_penilaian_id_sub_cpmk_sub_cpmk_id_sub_cpmk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
