# Generated by Django 4.1.4 on 2023-05-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0007_rename_id_jadwal_semester_sub_cpmk_id_nama_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpmk',
            name='tahun_angkatan',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_cpmk',
            name='tahun_angkatan',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
