# Generated by Django 4.1.4 on 2023-05-14 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0008_alter_cpmk_tahun_angkatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpmk',
            name='id_cpmk',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^\\S+$', 'Tidak boleh memiliki spasi')]),
        ),
    ]
