# Generated by Django 4.1.4 on 2023-05-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0009_alter_cpmk_id_cpmk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal_seminar',
            name='dosen_pembimbing_1',
        ),
        migrations.RemoveField(
            model_name='jadwal_seminar',
            name='dosen_pembimbing_2',
        ),
        migrations.RemoveField(
            model_name='jadwal_seminar',
            name='dosen_penguji_1',
        ),
        migrations.RemoveField(
            model_name='jadwal_seminar',
            name='dosen_penguji_2',
        ),
        migrations.RemoveField(
            model_name='jadwal_seminar',
            name='mahasiswa',
        ),
       
    ]
