# Generated by Django 4.1.4 on 2023-05-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0010_alter_jadwal_seminar_dosen_pembimbing_1_and_more'),
    ]

    operations = [
        
    ]
