# Generated by Django 4.1.4 on 2023-05-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0011_alter_jadwal_seminar_dosen_pembimbing_1_and_more'),
    ]

    operations = [

    ]
