# Generated by Django 4.1.4 on 2023-05-14 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0013_jadwal_seminar_dosen_pembimbing_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_pembimbing_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_1', to='skripsi_app.dosen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_pembimbing_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_2', to='skripsi_app.dosen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_penguji_1',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='penguji_1', to='skripsi_app.dosen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_penguji_2',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='penguji_2', to='skripsi_app.dosen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='mahasiswa',
            field=models.ForeignKey(default=23234, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='skripsi_app.mahasiswa'),
            preserve_default=False,
        ),
    ]
