# Generated by Django 4.1.4 on 2023-05-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0015_alter_jadwal_seminar_dosen_pembimbing_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpenilaian',
            name='id_jadwal_seminar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skripsi_app.jadwal_seminar'),
        ),
    ]
