# Generated by Django 4.1.4 on 2023-05-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0017_rename_id_jadwal_jadwal_seminar_id_jadwal_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_pembimbing_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_1', to='skripsi_app.roledosen'),
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_pembimbing_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_2', to='skripsi_app.roledosen'),
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_penguji_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penguji_1', to='skripsi_app.roledosen'),
        ),
        migrations.AlterField(
            model_name='jadwal_seminar',
            name='dosen_penguji_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penguji_2', to='skripsi_app.roledosen'),
        ),
    ]
