# Generated by Django 4.1.4 on 2023-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0018_alter_jadwal_seminar_dosen_pembimbing_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
