# Generated by Django 4.1.4 on 2023-05-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0020_alter_proposal_file_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal_semester',
            name='tahun_semester',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evaluasitopik',
            name='catatan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jadwal_semester',
            name='nama_semester',
            field=models.CharField(choices=[('Semester Ganjil', 'Semester Ganjil'), ('Semester Genap', 'Semester Genap')], default=None, max_length=60),
            preserve_default=False,
        ),
    ]
