# Generated by Django 4.1.4 on 2023-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0021_jadwal_semester_tahun_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpmk',
            name='keterangan_sub_cpmk',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='nama_tahap',
            field=models.CharField(choices=[('Proposal Awal', 'Proposal Awal '), ('Proposal Awal (Revisi Seminar Proposal)', 'Proposal Awal (Revisi Seminar Proposal)'), ('Laporan Akhir', 'Laporan Akhir '), ('Laporan Akhir (Revisi Seminar Hasil)', 'Laporan Akhir (evisi Seminar Hasil)')], max_length=60),
        ),
    ]
