# Generated by Django 4.1.4 on 2023-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0022_remove_cpmk_keterangan_sub_cpmk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulantopik',
            name='status_pengajuan',
            field=models.CharField(choices=[('Usulan Topik Pertama', 'Usulan Topik Pertama'), ('Pengajuan Kembali Usulan Topik', 'Pengajuan Kembali Usulan Topik')], default='Usulan Topik Pertama', max_length=60),
        ),
        migrations.AlterField(
            model_name='jadwal_semester',
            name='tahun_semester',
            field=models.CharField(default='Usulan Topik Pertama', max_length=100),
            preserve_default=False,
        ),
    ]
