# Generated by Django 4.1.4 on 2023-06-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi_app', '0023_usulantopik_status_pengajuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usulantopik',
            name='permintaan_dosen_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='skripsi_app.dosen'),
        ),
    ]
